spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identityforge_db
    username: postgres
    password: toor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9093
jwt:
  secret: ${JWT_SECRET}